### ISSUE TITLE
テストの記述

### ISSUE THREAD

**Issue by neila** [unchain-tech/ICP-Encrypted-Notes#10]
- [x] テストスクリプトを追加する
- [x] #15

**Comment by uukait** [comment]
CodeBuild上での動作確認済みです。
- [Build log](https://ap-northeast-1.console.aws.amazon.com/codesuite/codebuild/733910873054/projects/stg-codetest/build/stg-codetest%3Ad2a92430-7948-4695-86a3-d0006fa207bf/env_var?region=ap-northeast-1)

![Screen Shot 2023-09-22 at 17 28 19](https://github.com/unchain-tech/ICP-Encrypted-Notes/assets/60546319/02f4fe41-7814-4808-bb14-777e511cd9b3)
